spring:
  application:
    name: security-learning-app

#logging.org.springframework.security = TRACE

logging:
  level:
    org:
      springframework:
        security: TRACE


app:
  security:
    users:
      - username: user
        password: user123
        roles: USER
      - username: admin
        password: admin123
        roles: ADMIN
